// Builds data/world-map.js (the Actors page's world map) from Natural Earth
// data in the world-atlas package. Run from a folder with the packages
// installed:  npm install world-atlas@2 topojson-client d3-geo
// then:       node path/to/build_map.mjs && mv world-map.js path/to/data/
import { readFileSync, writeFileSync } from "fs";
import { feature, mesh } from "topojson-client";
import { geoEquirectangular, geoPath } from "d3-geo";
const land = JSON.parse(readFileSync("node_modules/world-atlas/land-110m.json"));
const countries = JSON.parse(readFileSync("node_modules/world-atlas/countries-110m.json"));
// Equirectangular, cropped to 84°N–58°S (no Antarctica); 1000 px wide
const W = 1000, TOP = 84, BOTTOM = -58;
const k = W / 360, H = Math.round((TOP - BOTTOM) * k);
const proj = geoEquirectangular().scale(W / (2 * Math.PI)).translate([W / 2, TOP * k]).precision(0.1);
const path = geoPath(proj).digits(1);
const landPath = path(feature(land, land.objects.land));
const borders = path(mesh(countries, countries.objects.countries, (a, b) => a !== b));
const out = `/* World map for the Actors page: land and country borders from Natural
   Earth (via world-atlas, 1:110m), in an equirectangular projection 1000
   wide, cropped to ${TOP}°N–${-BOTTOM}°S. Generated by scripts/build_map.mjs. */
window.CC_WORLD = ${JSON.stringify({ width: W, height: H, top: TOP, bottom: BOTTOM, land: landPath, borders })};
`;
writeFileSync("world-map.js", out);
console.log(W, H, out.length);
