#!/usr/bin/env python3
"""Build the member lists behind the Positions chamber diagrams.

Sources (download them, then pass their paths):
  UK  mySociety parlparse people.json
      https://raw.githubusercontent.com/mysociety/parlparse/master/members/people.json
  US  unitedstates/congress-legislators legislators-current.yaml
      https://raw.githubusercontent.com/unitedstates/congress-legislators/main/legislators-current.yaml

Usage:
  python3 scripts/build_members.py people.json legislators-current.yaml [YYYY-MM-DD]

Writes data/members-uk.js and data/members-us.js (window.CC_MEMBERS_UK / _US).
Each member is a compact array so the files stay small:
  UK: [id, name, party, constituency or "" for peers]
  US: [id, name, party, state, district (House) or class (Senate), first year in Congress]
"""
import datetime
import json
import sys
from pathlib import Path

import yaml  # pip install pyyaml

ROOT = Path(__file__).resolve().parent.parent


def current(m, day):
    return m.get("start_date", "") <= day <= m.get("end_date", "9999-12-31")


def name_on(person, day):
    names = [n for n in person.get("other_names", []) if n.get("note") == "Main" and current(n, day)]
    return names[-1] if names else (person.get("other_names") or [{}])[-1]


def lord_name(n):
    prefix, lordname, of = n.get("honorific_prefix", ""), n.get("lordname", ""), n.get("lordofname", "")
    if not lordname:  # bishops: "Bishop of Gloucester"
        return f"{prefix} of {of}".strip()
    return f"{prefix} {lordname}" + (f" of {of}" if of else "")


def build_uk(path, day):
    d = json.loads(Path(path).read_text())
    persons = {p["id"]: p for p in d["persons"]}
    posts = {p["id"]: p for p in d["posts"]}
    out = {"commons": [], "lords": []}
    for m in d["memberships"]:
        if not current(m, day):
            continue
        house = posts.get(m.get("post_id"), {}).get("organization_id") or m.get("organization_id")
        if house not in ("house-of-commons", "house-of-lords") or "person_id" not in m:
            continue
        n = name_on(persons[m["person_id"]], day)
        pid = m["person_id"].rsplit("/", 1)[-1]
        if house == "house-of-commons":
            name = f'{n.get("given_name", "")} {n.get("family_name", "")}'.strip()
            out["commons"].append([pid, name, m.get("on_behalf_of_id", ""), posts[m["post_id"]]["area"]["name"]])
        elif house == "house-of-lords":
            out["lords"].append([pid, lord_name(n), m.get("on_behalf_of_id", ""), ""])
    for k in out:
        out[k].sort(key=lambda r: r[1])
    return out


def build_us(path):
    d = yaml.safe_load(Path(path).read_text())
    out = {"senate": [], "house": []}
    for m in d:
        t = m["terms"][-1]
        name = m["name"].get("official_full") or f'{m["name"]["first"]} {m["name"]["last"]}'
        first = int(m["terms"][0]["start"][:4])
        if t["type"] == "sen":
            out["senate"].append([m["id"]["bioguide"], name, t["party"], t["state"], t.get("class", ""), first])
        else:
            out["house"].append([m["id"]["bioguide"], name, t["party"], t["state"], t.get("district", ""), first])
    for k in out:
        out[k].sort(key=lambda r: r[1])
    return out


def write(name, var, data, sources, day):
    header = (
        f"/* Generated by scripts/build_members.py on {datetime.date.today()} for {day}; do not edit.\n"
        f" * Source: {sources} */\n"
    )
    body = json.dumps(data, ensure_ascii=False, separators=(",", ":"))
    (ROOT / "data" / name).write_text(f"{header}window.{var} = {body};\n")


if __name__ == "__main__":
    uk_path, us_path = sys.argv[1], sys.argv[2]
    day = sys.argv[3] if len(sys.argv) > 3 else str(datetime.date.today())
    uk = build_uk(uk_path, day)
    us = build_us(us_path)
    write("members-uk.js", "CC_MEMBERS_UK", uk, "mySociety parlparse (github.com/mysociety/parlparse)", day)
    write("members-us.js", "CC_MEMBERS_US", us, "unitedstates/congress-legislators (github.com/unitedstates/congress-legislators)", day)
    print({k: len(v) for k, v in {**uk, **us}.items()})
